### ISSUE TITLE
eff... @jasdeepg has a virus

### ISSUE THREAD

**Issue by jasdeepg** [cyrusstoller/StartX-MedIC#11]
looks like it may not be the best for me (and you) to ball at this hackathon with you all this weekend. :(

i'm down to work on stuff from home, though, so feel free to throw things my way. don't want to get you guys sick, too.

love,
jas

**Comment by yosemitebandit** [comment]
Ah, sorry man..take it easy.  We'll tell the organizers you'll work remotely

**Comment by cyrusstoller** [comment]
Oh no! Feel better. We need to close this issue. Keep us posted.

**Comment by jasdeepg** [comment]
eff it. feel a lot better. i'm coming.
